# vim: ft=dockerfile
FROM opensuse/leap:15.1
LABEL maintainer="ncutler@suse.com"


RUN zypper addrepo http://download.suse.de/ibs/SUSE:/CA/openSUSE_Leap_15.1/SUSE:CA.repo
RUN zypper --non-interactive --gpg-auto-import-keys refresh
RUN zypper --non-interactive install --no-recommends \
        ca-certificates-suse \
        bzip2 \
        git-core \
        jq \
        osc \
        python3-pip \
        python3-virtualenv \
        tar \
        wget \
        sudo

RUN mkdir /builder
RUN useradd -m builder -d /builder
RUN echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

COPY oscrc /builder/.oscrc

RUN chown builder:users /builder/.oscrc
RUN chmod 600 /builder/.oscrc

USER builder
WORKDIR /builder

RUN osc --version
