FROM opensuse/leap:15.1
LABEL maintainer="ncutler@suse.com"


RUN true \
    && zypper addrepo http://download.suse.de/ibs/SUSE:/CA/openSUSE_Leap_15.1/SUSE:CA.repo \
#    && zypper addrepo https://download.opensuse.org/repositories/openSUSE:/Tools/openSUSE_15.1/openSUSE:Tools.repo
    && zypper --non-interactive --gpg-auto-import-keys refresh \
    && zypper --non-interactive install --no-recommends \
        ca-certificates-suse \
        bzip2 \
        git-core \
        jq \
        osc \
        python3-pip \
        python3-virtualenv \
        tar \
        gzip \
        wget \
        sudo

RUN useradd -m smithfarm \
    && echo "smithfarm ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

COPY oscrc /home/smithfarm/.oscrc

RUN chown smithfarm:users /home/smithfarm/.oscrc \
    && chmod 600 /home/smithfarm/.oscrc

USER smithfarm
WORKDIR /home/smithfarm 

RUN osc --version
