FROM hbjb-base:latest
LABEL maintainer="ncutler@suse.com"

COPY entrypoint.sh /builder/entrypoint.sh

USER builder
WORKDIR /builder

RUN sudo chmod 755 entrypoint.sh

ENTRYPOINT ["/builder/entrypoint.sh"]
