FROM make-rpm-base:latest
LABEL maintainer="ncutler@suse.com"

COPY entrypoint.sh /home/smithfarm/entrypoint.sh

USER smithfarm
WORKDIR /home/smithfarm

RUN sudo chmod 755 entrypoint.sh

ENTRYPOINT ["/home/smithfarm/entrypoint.sh"]
